# Generated by Django 4.2.16 on 2024-11-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slag',
            new_name='slug',
        ),
    ]
