# Generated by Django 4.2.16 on 2024-11-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_favorite_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('subscribe')), _negated=True), name='no_self_subscribe'),
        ),
    ]
